### ISSUE TITLE
VAR-SOM-MX7 base device tree contains evaluation kit specific entries

### ISSUE THREAD

**Issue by seppestas** [varigit/linux-imx#1]
The [VAR-SOM-MX7 base device tree (imx7d-var-som.dtsi)](../blob/imx_4.9.11_1.0.0_ga-var01/arch/arm/boot/dts/imx7d-var-som.dtsi) contains entries that are specific to the [VAR-STK-MX7 / VAR-DVK-MX7 evaluation kits](http://www.variscite.com/products/evaluation-kits/var-som-mx7-kits). This makes it harder than necessary to adept the device tree since it's pretty much required to patch the base device tree.

Notable devkit specific entries:
- [gpio-keys](https://github.com/varigit/linux-imx/blob/imx_4.9.11_1.0.0_ga-var01/arch/arm/boot/dts/imx7d-var-som.dtsi#L67)
- [the ov5640_mipi](https://github.com/varigit/linux-imx/blob/imx_4.9.11_1.0.0_ga-var01/arch/arm/boot/dts/imx7d-var-som.dtsi#L440)
- the [ft5x06_ts](https://github.com/varigit/linux-imx/blob/imx_4.9.11_1.0.0_ga-var01/arch/arm/boot/dts/imx7d-var-som.dtsi#L463)
- The [pcie_phy assuming an external PCI clock](https://github.com/varigit/linux-imx/blob/imx_4.9.11_1.0.0_ga-var01/arch/arm/boot/dts/imx7d-var-som.dtsi#L816)

Some of these devices are [documented  as being on the evaluation kit on the variscite wiki](http://variwiki.com/index.php?title=VAR-SOM-MX7_I2C#Variscite.27s_system_integrated_I2C_devices) but for other devices this is not very clear.

Having a generic dtsi device tree for the VAR_SOM-MX7 and a seperate dts device tree for the evaluation kits would make adapting the device tree for custom carriers a lot easier.

**Comment by varigigi** [comment]
Hi @seppestas,
thanks for the suggestion.
Since not preventing the SoM functionalities, we will consider it for next releases.
Best Regards
Pier

**Comment by varigigi** [comment]
Hi @seppestas,
as promised, we splitted the device tree to separate SoM and board settings.
You can find it here: https://github.com/varigit/linux-imx/commit/3c404d5fac2513d14edab9b7f19798d82de4f4f7
Best Regards
Pier

**Comment by seppestas** [comment]
Thanks a lot. I'm no longer involved with that project, but I still think it's a good idea!
