### ISSUE TITLE
Any plans to update to a newer v5.x series kernel?

### ISSUE THREAD

**Issue by cmorganBE** [varigit/linux-imx#14]
I have some drivers I'd like to pull in that are in v5.18 but the latest kernel here is v5.15. Any plans to update to something later in the 5 series?

**Comment by nsdrude** [comment]
@cmorganBE The [latest release from NXP](https://www.nxp.com/design/software/embedded-software/i-mx-software/embedded-linux-for-i-mx-applications-processors:IMXLINUX) is Linux 5.15.32_2.0.0​. Our Yocto Kirkstone release currently uses [5.15-2.0.x-imx_var01](https://github.com/varigit/linux-imx/tree/5.15-2.0.x-imx_var01), which is based on the fslc [5.15-2.0.x-imx](https://github.com/freescale/linux-fslc/tree/5.15-2.0.x-imx), which is based on NXP [lf-5.15.32-2.0.0](https://source.codeaurora.org/external/imx/linux-imx/log/?h=lf-5.15.32-2.0.0).

We have no plans to update to v5.18 until NXP officially supports it.

**Comment by cmorganBE** [comment]
@nsdrude ahh doh... I'll have to see how to get that stuff rebased then. thanks for the info.
