### ISSUE TITLE
Building rtl8188eus driver for dart-mx8mm

### ISSUE THREAD

**Issue by AlexMaddog13** [varigit/linux-imx#20]
Hello, I'm trying to build a driver for external Wi-Fi from this repo https://github.com/gglluukk/rtl8188eus. It successfully build on Ubuntu 20.04 and Raspberry Pi OS lite (32-bit). So, now I'm trying to do it with 5.4.142-g489e299ef3e9 from varigit. make process throw some error in kernel-headers which I downloaded with the command **_sudo apt-get install linux-headers-$(uname -r)_**. 
Could somebody suggest or give a guide on how to correctly build something related to kernel headers for mx8mm?

**Comment by nsdrude** [comment]
@AlexMaddog13 please open a ticket in Variscite's customer support portal: https://www.variscite.com/support/
