### ISSUE TITLE
 linux-variscite-5.15.71+gitAUTOINC+5ebe23fd15-r0 do_fetch: Failed to fetch in Yocto

### ISSUE THREAD

**Issue by GMunari** [varigit/linux-imx#22]
I got this error building yocto core-image-minimal for VAR-SOM-6UL:

ERROR: linux-variscite-5.15.71+gitAUTOINC+5ebe23fd15-r0 do_fetch: Fetcher failure: Fetch command export PSEUDO_DISABLED=1; export PATH="/workdir/build_wayland/tmp/sysroots-uninative/x86_64-linux/usr/bin:/workdir/sources/poky/scripts:/workdir/build_wayland/tmp/work/imx6ul_var_dart-fslc-linux-gnueabi/linux-variscite/5.15.71+gitAUTOINC+5ebe23fd15-r0/recipe-sysroot-native/usr/bin/arm-fslc-linux-gnueabi:/workdir/build_wayland/tmp/work/imx6ul_var_dart-fslc-linux-gnueabi/linux-variscite/5.15.71+gitAUTOINC+5ebe23fd15-r0/recipe-sysroot/usr/bin/crossscripts:/workdir/build_wayland/tmp/work/imx6ul_var_dart-fslc-linux-gnueabi/linux-variscite/5.15.71+gitAUTOINC+5ebe23fd15-r0/recipe-sysroot-native/usr/sbin:/workdir/build_wayland/tmp/work/imx6ul_var_dart-fslc-linux-gnueabi/linux-variscite/5.15.71+gitAUTOINC+5ebe23fd15-r0/recipe-sysroot-native/usr/bin:/workdir/build_wayland/tmp/work/imx6ul_var_dart-fslc-linux-gnueabi/linux-variscite/5.15.71+gitAUTOINC+5ebe23fd15-r0/recipe-sysroot-native/sbin:/workdir/build_wayland/tmp/work/imx6ul_var_dart-fslc-linux-gnueabi/linux-variscite/5.15.71+gitAUTOINC+5ebe23fd15-r0/recipe-sysroot-native/bin:/workdir/sources/poky/bitbake/bin:/workdir/build_wayland/tmp/hosttools"; export HOME="/home/vari"; LANG=C git -c core.fsyncobjectfiles=0 -c gc.autoDetach=false -c core.pager=cat clone --bare --mirror https://github.com/varigit/linux-imx /workdir/downloads//git2/github.com.varigit.linux-imx --progress failed with exit code 128, no output
ERROR: linux-variscite-5.15.71+gitAUTOINC+5ebe23fd15-r0 do_fetch: Bitbake Fetcher Error: FetchError('Unable to fetch URL from any source.', 'git://github.com/varigit/linux-imx;protocol=https;branch=lf-5.15.y_var01')
ERROR: Logfile of failure stored in: /workdir/build_wayland/tmp/work/imx6ul_var_dart-fslc-linux-gnueabi/linux-variscite/5.15.71+gitAUTOINC+5ebe23fd15-r0/temp/log.do_fetch.147
ERROR: Task (/workdir/sources/meta-variscite-bsp/recipes-kernel/linux/linux-variscite_5.15.bb:do_fetch) failed with exit code '1'

Trying to clone the linux-imx repository it fails if DEPTH is set greater than 1.

It seems not to be a network problem.

**Comment by varigigi** [comment]
@GMunari, as far as I can see, github is reachable as well as the specific commit it https://github.com/varigit/linux-imx/commit/5ebe23fd15.
If I copy and paste the command (just changing the local paths), it works just fine here.
I would suggest checking the router log of the company for possible connectivity problems.
I'm closing this issue as not reproducible in our labs.
Best Regards
