### ISSUE TITLE
hello_world demo app stops working on m33 after linux boots

### ISSUE THREAD

**Issue by philflex2020** [varigit/linux-imx#23]
Load and run the hello_world binary under u-boot.
The system sends a hello world. message and responds to data from the uart ( note its on pins 3 and 5 on the symphonny module ) 
Boot into linux.
The Uart stops responding.
The remoteproc state responds with "attached".

Reboot the system without the m33 running and the remoteproc services run as expected, you can load /reload the firmware and start / stop the m33 as expected.

**Comment by nsdrude** [comment]
@philflex2020 Please provide the full steps to reproduce this issue, including which SOM, which software release, and which Linux device tree you are using.
