### ISSUE TITLE
Booting hangs with `imx6q-pcie 33800000.pcie: PCIe PLL is locked.` message

### ISSUE THREAD

**Issue by bessszilard** [varigit/linux-imx#25]
Hello! I downloaded the kernel version 5.15-2.0.x-imx_var01 for Kirkstone as recommended in [1]. I successfully built it using commit a10598220c20e5b259f03e110edae4489f6df188 from the following branch: https://github.com/varigit/linux-imx/commits/5.15-2.0.x-imx_var01/. After flashing the SWU image onto the Variscite imx8mq-var-dart board [3], the boot process stopped with the message: `imx6q-pcie 33800000.pcie: PCIe PLL is locked`. The full boot log is available at [4]. Notably, the board was working correctly with the Yocto Dunfell build [5].

Could you please advise on how to resolve this issue?

Thank,
Szilard B

[1] https://variwiki.com/index.php?title=DART-MX8M_Release_Notes&release=mx8m-yocto-kirkstone-5.15-2.0.x-v1.5

[2]
![ksnip_20240911-094506](https://github.com/user-attachments/assets/6f19cb9c-b1aa-47a9-b328-17888bf69c44)

[3] https://variwiki.com/index.php?title=DART-MX8M

[4] [hanged_boot_def_kernel.txt](https://github.com/user-attachments/files/16964129/hanged_boot_def_kernel.txt)

[5]
```
LINUX_VERSION = "5.4.142"
SRCBRANCH = "5.4-2.1.x-imx_var01"
SRCREV = "3a0c66906337ae09b95c63666ac3bf9be60fdfaa"
```

**Comment by nsdrude** [comment]
@bessszilard Please open a ticket using Variscite's customer support portal: https://www.variscite.com/support/
