### ISSUE TITLE
SN65DSI83 Driver

### ISSUE THREAD

**Issue by tstockk** [varigit/linux-imx#5]
Hay, 

i patched the SN65DSI83 Driver in a newer Kernel Version (4.14.98_2.0.0_ga) from NXP for the 8MM.
The driver looks working without Issues but i get no picture. All Registers looking fine.

**Comment by eranmati** [comment]
Hi.
Please use the Variscite customer portal:
https://varisciteportal.axosoft.com/login

Regards,
Eran
