### ISSUE TITLE
Keyctl issue

### ISSUE THREAD

**Issue by dpatil89** [varigit/linux-imx#8]
**Setup:**
**SoC : imx7d
SoM : imx7-var-som
kernel version:5.4.127
keyutils version :1.6.1**

Please find the attached kernel configuration(kernel_configuration.txt).

I am following AN12714 given by NXP[latest version] for encryption storage using CAAM secure keys.

I configure kernel as mentioned in application note and caam-keygen device registered correctly.

**root@imx7-var-som:~# dmesg | grep caam
[    0.504972] caam 30900000.caam: Entropy delay = 3200
[    0.564417] caam 30900000.caam: Instantiated RNG4 SH0
[    0.623846] caam 30900000.caam: Instantiated RNG4 SH1
[    0.623870] caam 30900000.caam: device ID = 0x0a16030000000000 (Era 8)
[kernel_config.txt](https://github.com/varigit/linux-imx/files/7649458/kernel_config.txt)
[kernel_config.txt](https://github.com/varigit/linux-imx/files/7649461/kernel_config.txt)

[    0.623879] caam 30900000.caam: job rings = 3, qi = 0
[    0.635929] caam algorithms registered in /proc/crypto
[    0.637547] caam 30900000.caam: caam pkc algorithms registered in /proc/crypto
[    0.637567] caam 30900000.caam: registering rng-caam
[    0.683685] Device caam-keygen registered**
 
I have successfully generated keys using caam-keygen.

I successfully added a key based on the generated black key in the key retention service using "keyctl"

Following is the output:

**root@imx7-var-som:/# cat /data/caam/randomkey | keyctl padd logon logkey: @s
765699361**

but when I check using keyctl then same id doesn't appear

Following is output:

**root@imx7-var-som:/# keyctl list @s
1 key in keyring:
24465593: --alswrv 0 65534 keyring: _uid.0**

I also followed the old version of AN12714 but getting following error:
**add_key: No such device**
 
Please guide me to resolve the issue.

Regards,
dpatil

**Comment by varigigi** [comment]
Dear Dhananjay,
we never released/tested any kernel release based on kernel 5.4.127
Please align to any valid release.
Thanks
Best Regards
Pier

**Comment by dpatil89** [comment]
Hi Pier,
I am using 5.4-2.3.x-imx_var01 branch.
It's kernel version is 5.4.127.
Regards,
Dhananjay Patil

**Comment by varigigi** [comment]
Dear Dhananjay,
you may want to check our wiki pages for VAR-SOM-MX7
    https://variwiki.com/index.php?title=VAR-SOM-MX7
We never released/tested any kernel release based on kernel 5.4.127
Please align to any valid release.
Thanks
Best Regards
Pier

**Comment by dpatil89** [comment]
Thanks Pier,
I just checked the version on https://variwiki.com/index.php?title=VAR-SOM-MX7
its 5.4.142.
Before proceeding with this version I want to confirm that this version is released and tested by Variscite Team.
Regards,
Dhananjay Patil

**Comment by varigigi** [comment]
Dear Dhananjay,
we confirm that we performed all the standard tests reported in the [How-to](https://variwiki.com/index.php?title=VAR-SOM-MX7_Yocto&release=RELEASE_DUNFELL_V1.2_VAR-SOM-MX7) section of Yocto wiki pages.
Be aware that
- [AN12714](https://community.nxp.com/t5/i-MX-Processors/Kernel-version-for-AN12714-i-MX-Encrypted-Storage-Using-CAAM/m-p/1258883) refers to NXP iMX8MM and NXP kernel 5.4.47 v2.2.0
- you are going to use VAR-SOM-MX7 (based on NXP iMX7D) and kernel 5.4.142 (based on NXP kernel 5.4.24 v2.1.0)

If you need dedicated help, you may want to contact our sales at sales@variscite.com
Best Regards
Pier

**Comment by dpatil89** [comment]
Hi Pier,
I understand that you are suggesting to use NXP kernel for AN12714 and this feature is not tested by Variscite.
Regards,
Dhananjay Patil

**Comment by varigigi** [comment]
Dear Dhananjay,
I'm also suggesting that not even NXP tested this against iMX7D.
Best Regards
Pier
