### ISSUE TITLE
NXP kernel version of Variscite Linux Kernel

### ISSUE THREAD

**Issue by dpatil89** [varigit/linux-imx#9]
I am using the Linux kernel provided by variscite 5.4-2.1.x-imx_var01.
On which NXP Linux Kernel version this release is based on?

**Comment by varigigi** [comment]
Hi @dpatil89,
it is based on NXP branch [imx_5.4.24_2.1.0](https://source.codeaurora.org/external/imx/linux-imx/?h=imx_5.4.24_2.1.0).
Any issue or can we close this?
Thanks
BR
Pier

**Comment by eranmati** [comment]
@dpatil89 , it is based on FSL community branch 5.4-2.1.x-imx, which is based on NXP’s Linux 5.4.24_2.1.0 release and the Linux mainline kernel 5.4.142.
